name: 'Install Linkerd'
description: 'installs linkerd onto target cluster'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/install-kubectl.sh
      shell: bash
    - run: ${{ github.action_path }}/install-osm.sh
      shell: bash